service: media-hub

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  environment:
    USER_TABLE: ${env:USER_TABLE}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:Scan
        - dynamodb:Query
      Resource:
        - arn:aws:dynamodb:us-east-1:*:table/${env:USER_TABLE}

functions:
  getUserProfile:
    handler: functions/src/getUserProfile.handler
    events:
      - http:
          path: users/{userId}
          method: get
          cors: true

  createUser:
    handler: functions/src/createUser.handler
    events:
      - http:
          path: users
          method: post
          cors: true

package:
  patterns:
    - ../functions/src/**

resources:
  Resources:
    UserTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${env:USER_TABLE}
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
